server: 
  port: 9001
  
 spring:
  h2:
    console:
      enabled: true
      
#    datasource:
#      driver-class-name: org.h2.Driver
#      url: jdbc:h2:file:c:/temp/test-db
#      username: sa
#      password:
#      
#	  jpa:
#	    database-platform: org.hibernate.dialect.H2Dialect
#	    hibernate:
#	      ddl-auto: create-drop

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@DESKTOP-IEDEJ5T:1521/XE
    username: hr
    password: hr
    
  jpa: 
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop